### ISSUE TITLE
Access Epic

### ISSUE THREAD

**Issue by Karolill** [olemagnusnorum/kundestyrt-prosjekt-gruppe-12#4]
Everyone must be able to log in to the epic sandbox. Talk to Babak about this, possibly look for him in his office

- [x] Amund
- [x] Karoline
- [x] Kenny
- [x] Magnus
- [x] Markus
- [x] Matias
- [x] Ole Marius
- [x] Ole-Magnus

**Comment by amundstorruste** [comment]
Folk bør sjekke om de kan logge på før vi er ferdige med denne issuen.
