### ISSUE TITLE
Figure out which two types of communication with epic to implement for the user stories

### ISSUE THREAD

**Issue by Karolill** [olemagnusnorum/kundestyrt-prosjekt-gruppe-12#9]
We need to:
- [x] Explore epic
- [x] Decide two ways of communication with epic
- [x] Decide which project to use which type of communication on

**Comment by amundstorruste** [comment]
1) Subsribe to due dates for child births
2) Ping pong communication regarding sick-note (sykemelding)
- Pasient starter hos NAV
- NAV spør legen om informasjon
- Legen sier til NAV at Informasjon mangler
- NAV sier til kunde at de må gå til legen
- Pasient hos lege
- Lege sier til NAV at .......
- Etc.

**Comment by amundstorruste** [comment]
See above comment
